[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "zenith-editor"
version = "1.0.0"
description = "Code editor built in Python and PySide6"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "PySide6>=6.0.0"
]

[project.scripts]
zenith = "zenith.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"zenith" = ["icons/*.png"]